.. image:: images/logo_small.svg

* Pyvib

This repository contains the pyvib packages. A python library for nonlinear
state space modeling using white-, gray- and blackbox models. See the
[[https://pyvib.readthedocs.io][documentation]] for further info.


** Resources

- [[https://pyvib.readthedocs.io][API documentation]] - technical details on all functions
- [[https://github.com/pawsen/pyvib/tree/master/doc/Tutorial/Getting%20Started.ipynb][Getting-started
  guide]] - tutorial page (run with [[http://jupyter.org/][jupyter]] to get interactive
   features)
- [[https://github.com/pawsen/pyvib/tree/master/examples][Examples page]] -
  stand-alone executables of different applications

** Dependencies

*** Required

This library requires numpy, scipy and python3.7. E.g. on Linux:

#+BEGIN_SRC sh
  pip install numpy, scipy
#+END_SRC

** nixos

Use =flake.nix= to setup a development env on nix.

Use either
: nix develop
to an environment with black/isort/pyright

or
: nix build
to get a link to the package in =./result=

** Useful Links
Although this package does not have anything to do with control, state space
models are often used for this. See these packages for more(taken from harold)

- There is already an almost-matured control toolbox which is led by
  Richard Murray et al. and it can perform
  already most of the essential tasks. Hence, if you want to have
  something that resembles the basics of matlab control toolbox, you should give
  it a try. However, it is somewhat limited to SISO tools and also relies on
  SLICOT library which can lead to installation hassle and/or licensing
  problems for nontrivial tasks.
  https://github.com/python-control/python-control

- You can also use the tools available in SciPy ``signal`` module for basics
  of LTI system manipulations. SciPy is a powerful all-purpose scientific
  package. This makes it extremely useful however admittedly every discipline
  has a limited presence hence the limited functionality. If you are looking
  for a quick LTI system manipulation and don't want to install yet another
  package, then it might be the tool for you.
  https://docs.scipy.org/doc/scipy/reference/signal.html

- Instead, if you are interested in robust control you probably would
  appreciate the `Skogestad-Python`_ project. They are replicating the
  code parts of the now-classic book completely in Python. Awesome!
  https://github.com/alchemyst/Skogestad-Python

- harold
  MIMO systems and without dependency for SLICOT
  https://github.com/ilayn/harold/
